[package]
name = "rusty_med_view"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = { version = "27", features = ["webgl"] }
winit = "0.30"
pollster = "0.3"
bytemuck = { version = "1.14", features = ["derive"] }
hecs = "0.10"
egui = "0.33"
egui-wgpu = "0.33"
egui-winit = { version = "0.33", default-features = false, features = ["links"] }
log = "0.4"
env_logger = "0.11"
web-time = "1.1"
glam = "0.29"

# NIfTI medical image loading
nifti = { version = "0.17", default-features = false }
thiserror = "2"
rfd = "0.15"
flate2 = "1.0"
uuid = { version = "1.19.0", features = ["v4", "js"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["Window", "Document", "Element", "HtmlCanvasElement", "console", "HtmlInputElement", "File", "FileReader", "FileList", "Blob"] }
console_error_panic_hook = "0.1"
console_log = "1.0"
